// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdOVU17EsQCUKpMOEIc4eC3JAWd6bEY6A',
    appId: '1:113975548809:web:00b422860431b73bd4df58',
    messagingSenderId: '113975548809',
    projectId: 'wedive-8588c',
    authDomain: 'wedive-8588c.firebaseapp.com',
    storageBucket: 'wedive-8588c.firebasestorage.app',
    measurementId: 'G-9Q512QWDLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZKT4ub0iz8XeUD6FigD9raJOq5j3e5Is',
    appId: '1:113975548809:android:82db5ec71644ea37d4df58',
    messagingSenderId: '113975548809',
    projectId: 'wedive-8588c',
    storageBucket: 'wedive-8588c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMvw5V7mZkqQm4USucO7RnQnyksw0xAZA',
    appId: '1:113975548809:ios:dfafb7f2c7a05561d4df58',
    messagingSenderId: '113975548809',
    projectId: 'wedive-8588c',
    storageBucket: 'wedive-8588c.firebasestorage.app',
    androidClientId: '113975548809-1ma8qqq3hijubsgt7epbonktlkfqcfbj.apps.googleusercontent.com',
    iosClientId: '113975548809-gm6i76132lh23c6fgt0mnmjeocdit5ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMvw5V7mZkqQm4USucO7RnQnyksw0xAZA',
    appId: '1:113975548809:ios:dfafb7f2c7a05561d4df58',
    messagingSenderId: '113975548809',
    projectId: 'wedive-8588c',
    storageBucket: 'wedive-8588c.firebasestorage.app',
    androidClientId: '113975548809-1ma8qqq3hijubsgt7epbonktlkfqcfbj.apps.googleusercontent.com',
    iosClientId: '113975548809-gm6i76132lh23c6fgt0mnmjeocdit5ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.wedive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdOVU17EsQCUKpMOEIc4eC3JAWd6bEY6A',
    appId: '1:113975548809:web:b5bd8a8dc116201ed4df58',
    messagingSenderId: '113975548809',
    projectId: 'wedive-8588c',
    authDomain: 'wedive-8588c.firebaseapp.com',
    storageBucket: 'wedive-8588c.firebasestorage.app',
    measurementId: 'G-Q6RWVG2GMN',
  );

}